apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: layer-virtualization
  annotations:
    rosa-gitops-layer: virtualization
    rosa-gitops-description: "OpenShift Virtualization (KubeVirt) for running VMs on OpenShift"

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - hyperconverged.yaml

commonLabels:
  app.kubernetes.io/part-of: rosa-gitops-layers
  app.kubernetes.io/component: virtualization
  rosa-gitops-layer: virtualization
