apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: layer-terminal
  annotations:
    rosa-gitops-layer: terminal
    rosa-gitops-description: "OpenShift Web Terminal operator for in-console CLI access"

resources:
  - namespace.yaml
  - subscription.yaml

commonLabels:
  app.kubernetes.io/part-of: rosa-gitops-layers
  app.kubernetes.io/component: terminal
  rosa-gitops-layer: terminal
